redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis
test: *redis
production:
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: menu-api-overview_production
